version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: ugB<$20^6If+
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data
    restart: always

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ryEb9yr87S/D
      POSTGRES_DB: seplag-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seplag-api
    depends_on:
      - postgres
    ports:
      - "8080:80"
    environment:
      CI_ENVIRONMENT: development
      DB_HOST: postgres
      DB_NAME: seplag-db
      DB_USER: user
      DB_PASS: ryEb9yr87S/D
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: ugB<$20^6If+
    volumes:
      - .:/var/www/html
    entrypoint: ["/var/www/html/docker-entrypoint.sh"]

volumes:
  minio_data:
  postgres_data:
