version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: seplag@123
    command: server /data --console-address ":9001"
    networks:
      - app_network

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: seplag
      POSTGRES_PASSWORD: seplag@123
      POSTGRES_DB: seplag_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    build: .
    container_name: app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
      - minio
    networks:
      - app_network

networks:
  app_network:
    driver: bridge